import Navbar from './Components/Navbar'
import "./Components/navbar.css"
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
       {children}
       <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
<df-messenger
  intent="WELCOME"
  chat-title="HealthBot"
  agent-id="8a052415-abf8-47d5-b18f-59d6589fbc6c"
  language-code="en"
></df-messenger>

        </body>
    </html>
  )
}
